# Generated by Django 2.1.5 on 2020-03-01 20:25

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_number', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_version', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_revision', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_type', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_lang', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_created_at', models.DateField(blank=True)),
                ('document_last_edition', models.DateField(blank=True)),
                ('document_last_publication', models.DateField(blank=True)),
                ('document_revised_modified', models.DateField(blank=True)),
                ('document_link', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('maps_link', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('document_category', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='guest', max_length=254)),
                ('image', models.ImageField(default='portraits/default.jpg', upload_to=core.utils.content_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier', models.CharField(max_length=254, unique=True)),
                ('product_name', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('product_brand', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('product_category', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('product_code', models.TextField(default='Not Specified')),
                ('product_series', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('product_part_number', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('business', models.CharField(blank=True, default='Not Specified', max_length=254)),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductModel'),
        ),
    ]
