# Generated by Django 2.1.5 on 2020-03-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='product_identifier',
            new_name='product',
        ),
    ]
