# Generated by Django 2.1.5 on 2020-02-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
