# Generated by Django 2.1.5 on 2020-03-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200308_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='core.DocumentModel'),
        ),
    ]
